/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu;

import java.awt.Color;
import javax.swing.JOptionPane;
import pitstop.OrdenServicio;
import pitstop.SqLite;

/**
 *
 * @author edwin
 */
public class Aviso extends javax.swing.JPanel {
    int ordenId;
    public MenuPrincipal restore;
    /**
     * Creates new form Aviso
     */
    public Aviso(int ordenId) {
        initComponents();
        this.ordenId = ordenId;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAviso = new javax.swing.JPanel();
        pTiposDatos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cbProceso = new javax.swing.JCheckBox();
        cbTerminado = new javax.swing.JCheckBox();
        cbEntregado = new javax.swing.JCheckBox();
        bEditar = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        tVehiculo = new javax.swing.JTextField();
        tFecha = new javax.swing.JTextField();
        tServicio = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setMaximumSize(new java.awt.Dimension(530, 160));
        setMinimumSize(new java.awt.Dimension(480, 160));
        setPreferredSize(new java.awt.Dimension(530, 160));

        pAviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pAviso.setAlignmentX(0.0F);
        pAviso.setMaximumSize(new java.awt.Dimension(510, 140));
        pAviso.setMinimumSize(new java.awt.Dimension(480, 140));
        pAviso.setPreferredSize(new java.awt.Dimension(510, 140));
        pAviso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAvisoMouseClicked(evt);
            }
        });

        pTiposDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pTiposDatos.setMaximumSize(new java.awt.Dimension(108, 126));

        jSeparator1.setMaximumSize(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vehiculo");

        jSeparator4.setMaximumSize(null);

        jLabel3.setText("Fecha de entrega");

        jSeparator5.setMaximumSize(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Servicio");

        javax.swing.GroupLayout pTiposDatosLayout = new javax.swing.GroupLayout(pTiposDatos);
        pTiposDatos.setLayout(pTiposDatosLayout);
        pTiposDatosLayout.setHorizontalGroup(
            pTiposDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTiposDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTiposDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTiposDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(pTiposDatosLayout.createSequentialGroup()
                .addGroup(pTiposDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTiposDatosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTiposDatosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTiposDatosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pTiposDatosLayout.setVerticalGroup(
            pTiposDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTiposDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        cbProceso.setText("En proceso");
        cbProceso.setMaximumSize(new java.awt.Dimension(70, 24));
        cbProceso.setMinimumSize(new java.awt.Dimension(70, 24));
        cbProceso.setPreferredSize(new java.awt.Dimension(70, 24));
        cbProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProcesoActionPerformed(evt);
            }
        });

        cbTerminado.setText("Terminado");
        cbTerminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTerminadoActionPerformed(evt);
            }
        });

        cbEntregado.setText("Entregado");
        cbEntregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEntregadoActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        tNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        tVehiculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tVehiculoActionPerformed(evt);
            }
        });

        tFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFechaActionPerformed(evt);
            }
        });

        tServicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tServicio.setMinimumSize(new java.awt.Dimension(15, 18));
        tServicio.setPreferredSize(new java.awt.Dimension(15, 18));
        tServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAvisoLayout = new javax.swing.GroupLayout(pAviso);
        pAviso.setLayout(pAvisoLayout);
        pAvisoLayout.setHorizontalGroup(
            pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTiposDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tFecha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bEditar)
                        .addComponent(cbTerminado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbEntregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pAvisoLayout.setVerticalGroup(
            pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTiposDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAvisoLayout.createSequentialGroup()
                        .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(8, 8, 8)
                        .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTerminado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tVehiculo))
                        .addGap(8, 8, 8)
                        .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEntregado)
                            .addComponent(tFecha, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(8, 8, 8)
                        .addGroup(pAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAvisoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tFecha, tNombre, tServicio, tVehiculo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(88, Short.MAX_VALUE)
                    .addComponent(pAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(86, 86, 86)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(pAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        EditarOrden editar = new EditarOrden(restore, ordenId);
        editar.setVisible(true);
    }//GEN-LAST:event_bEditarActionPerformed

    private void cbEntregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEntregadoActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "¿Estas seguro?","Confirmacion",0);
        if (a == 0){
            cambiarEstatus(OrdenServicio.Estatus.Entregada);
            restore.generarInfo();
        }else {
            cbEntregado.setSelected(false);
        }
        desactivado();
    }//GEN-LAST:event_cbEntregadoActionPerformed

    private void cbTerminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTerminadoActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "¿Estas seguro?","Confirmacion",0);
        if (a == 0){
            cambiarEstatus(OrdenServicio.Estatus.Terminada);
            restore.generarInfo();
        }else {
            cbTerminado.setSelected(false);
        }
        desactivado();
    }//GEN-LAST:event_cbTerminadoActionPerformed

    private void cbProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProcesoActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "¿Estas seguro?","Confirmacion",0);
        if (a == 0){
            cambiarEstatus(OrdenServicio.Estatus.Proceso);
            restore.generarInfo();
        }else {
            cbProceso.setSelected(false);
        }
        desactivado();
    }//GEN-LAST:event_cbProcesoActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void tServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tServicioActionPerformed

    private void tVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tVehiculoActionPerformed

    private void tFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFechaActionPerformed

    private void pAvisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAvisoMouseClicked
        // TODO add your handling code here:
        InfoOrden nuevo = new InfoOrden(ordenId);
        nuevo.setVisible(true);
    }//GEN-LAST:event_pAvisoMouseClicked
    
    private void desactivado(){ 
        if (!cbEntregado.isEnabled() && !cbTerminado.isEnabled() && !cbProceso.isEnabled()) {
            //pAviso.setVisible(false);
            restore.pMarco.remove(this);
            restore.pMarco.revalidate();
            restore.pMarco.repaint();
        }
    }
    
    private void cambiarEstatus(pitstop.OrdenServicio.Estatus estatus){
        SqLite sql = new SqLite();
        OrdenServicio orden = sql.RetrieveOrdenServicio("Select * From OrdenesServicio Where idOrden = " + ordenId).get(0);
        if(estatus.compareTo(orden.getEstatusActual()) > 0){
            orden.setEstatusActual(estatus);
            orden.Update();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bEditar;
    public javax.swing.JCheckBox cbEntregado;
    public javax.swing.JCheckBox cbProceso;
    public javax.swing.JCheckBox cbTerminado;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JPanel pAviso;
    public javax.swing.JPanel pTiposDatos;
    public javax.swing.JTextField tFecha;
    public javax.swing.JTextField tNombre;
    public javax.swing.JTextField tServicio;
    public javax.swing.JTextField tVehiculo;
    // End of variables declaration//GEN-END:variables
}
