/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import pitstop.tablas;

/**
 *
 * @author edwin
 */
public class Empleados extends javax.swing.JFrame {
    public tablas tablas = new tablas();
    public int idEmpleado;
    public boolean valor;
    
    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        desactivarEdicion();
        tablas();        
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tTecnicos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAsesores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bEditarTecnico = new javax.swing.JButton();
        bEditarAsesor = new javax.swing.JButton();
        bAgregarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(700, 500));

        tTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTecnicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTecnicos);

        tAsesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAsesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAsesoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tAsesores);

        jLabel1.setText("Tecnicos");

        jLabel2.setText("Asesores");

        bEditarTecnico.setText("Editar Tecnicos");
        bEditarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarTecnicoActionPerformed(evt);
            }
        });

        bEditarAsesor.setText("Editar Asesores");
        bEditarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarAsesorActionPerformed(evt);
            }
        });

        bAgregarEmpleado.setText("Agregar Empleado");
        bAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEditarTecnico))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEditarAsesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAgregarEmpleado))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(bEditarTecnico)
                    .addComponent(bAgregarEmpleado)
                    .addComponent(bEditarAsesor))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEditarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarAsesorActionPerformed
        // TODO add your handling code here:
        valor = true;
        NuevoEmpleado nuevo = new NuevoEmpleado(valor,idEmpleado);
            nuevo.btnAceptar.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt){
                tablas();
            }
        });
        nuevo.setVisible(true);
        tAsesores.clearSelection();
        tTecnicos.clearSelection();
    }//GEN-LAST:event_bEditarAsesorActionPerformed

    private void bAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        valor = false;
        NuevoEmpleado nuevo = new NuevoEmpleado(valor,idEmpleado);
            nuevo.btnAceptar.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt){
                tablas();
            }
        });
        nuevo.setVisible(true);
    }//GEN-LAST:event_bAgregarEmpleadoActionPerformed

    private void bEditarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarTecnicoActionPerformed
        // TODO add your handling code here:
        boolean value = true;
        NuevoEmpleado nuevo = new NuevoEmpleado(value,idEmpleado);
            nuevo.btnAceptar.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt){
                tablas();
            }
        });
        nuevo.setVisible(true);
        tAsesores.clearSelection();
        tTecnicos.clearSelection();
    }//GEN-LAST:event_bEditarTecnicoActionPerformed

    private void tTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTecnicosMouseClicked
        // TODO add your handling code here:
        int row = tTecnicos.rowAtPoint(evt.getPoint());
        int id = Integer.parseInt(tTecnicos.getModel().getValueAt(row, 1).toString());
        idEmpleado = id;
    }//GEN-LAST:event_tTecnicosMouseClicked

    private void tAsesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAsesoresMouseClicked
        // TODO add your handling code here:
        int row = tAsesores.rowAtPoint(evt.getPoint());
        int id = Integer.parseInt(tAsesores.getModel().getValueAt(row, 1).toString());
        idEmpleado = id;
    }//GEN-LAST:event_tAsesoresMouseClicked

    public void desactivarEdicion(){
        tTecnicos.setDefaultEditor(Object.class, null); 
        tAsesores.setDefaultEditor(Object.class, null);
    }
    
    public void tablas(){
        tablaTecnicos();
        tablaAsesores();
    }
    public void tablaTecnicos(){
        tablas.llenadoTablaTecnicos(tTecnicos);
    }
    public void tablaAsesores(){
        tablas.llenadoTablaAsesores(tAsesores);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarEmpleado;
    private javax.swing.JButton bEditarAsesor;
    private javax.swing.JButton bEditarTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tAsesores;
    private javax.swing.JTable tTecnicos;
    // End of variables declaration//GEN-END:variables
}
