/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import pitstop.Asesor;
import pitstop.Cliente;
import pitstop.Empleado;
import pitstop.SqLite;
import pitstop.Tecnico;
/**
 *
 * @author edwin
 */
public class NuevoEmpleado extends javax.swing.JFrame {
    public boolean open;
    public int id;
    public Tecnico.nivel nivel;
    /**
     * Creates new form NuevoEmpleado
     */
    public NuevoEmpleado(boolean open, int id) {
        initComponents();
        this.open = open;
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cbbTipoEmpleado = new javax.swing.JComboBox<>();
        cbbNivel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setText("Email");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombres");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido Paterno");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Empleado");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Telefono");

        jLabel7.setText("Tipo");

        cbbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asesor", "Tecnico" }));
        cbbTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTipoEmpleadoActionPerformed(evt);
            }
        });

        cbbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Master" }));
        cbbNivel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(txtApellidoP)
                        .addComponent(txtNombre)
                        .addComponent(txtEmail)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cbbTipoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String niveles = cbbNivel.getSelectedItem().toString();
        String tipo = cbbTipoEmpleado.getSelectedItem().toString();
        if (tipo.equals("Tecnico")){
            if (open){
                String nombre = txtNombre.getText();
                String apellidoP = txtApellidoP.getText();
                String apellidoM = txtApellidoM.getText();
                String telefono = txtTelefono.getText();
                String eMail = txtEmail.getText();
                nivel = Tecnico.nivel.valueOf(niveles);
                Tecnico empleado = new Tecnico(id, nombre, apellidoP, apellidoM, telefono, eMail,nivel);
                empleado.Update();
            } else {
                String nombre = txtNombre.getText();
                String apellidoP = txtApellidoP.getText();
                String apellidoM = txtApellidoM.getText();
                String telefono = txtTelefono.getText();
                String eMail = txtEmail.getText();
                nivel = Tecnico.nivel.valueOf(niveles);
                Tecnico empleado = new Tecnico(id, nombre, apellidoP, apellidoM, telefono, eMail,nivel);
                empleado.Create();
            }
        }else{
            if (open){
                String nombre = txtNombre.getText();
                String apellidoP = txtApellidoP.getText();
                String apellidoM = txtApellidoM.getText();
                String telefono = txtTelefono.getText();
                String eMail = txtEmail.getText();
                Asesor empleado = new Asesor(id, nombre, apellidoP, apellidoM, telefono, eMail);
                empleado.Update();
            } else {
                String nombre = txtNombre.getText();
                String apellidoP = txtApellidoP.getText();
                String apellidoM = txtApellidoM.getText();
                String telefono = txtTelefono.getText();
                String eMail = txtEmail.getText();
                Asesor empleado = new Asesor(id, nombre, apellidoP, apellidoM, telefono, eMail);
                empleado.Create();
            }   
        }
        

        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbbTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTipoEmpleadoActionPerformed
        // TODO add your handling code here:
        if(cbbTipoEmpleado.getSelectedItem().toString().equals("Tecnico")){
            cbbNivel.setEnabled(true);
        }
    }//GEN-LAST:event_cbbTipoEmpleadoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (open){
            editarCliente(id);
        }
    }//GEN-LAST:event_formWindowOpened
    
    public void editarCliente(int id){
        SqLite sql = new SqLite();
        
        ArrayList<Asesor> asesor = sql.RetrieveAsesores("select * from Empleados");
        for(Asesor asesores : asesor){
            if (asesores.getId() == id){
                txtNombre.setText(asesores.getNombre());
                txtApellidoP.setText(asesores.getApellidoP());
                txtApellidoM.setText(asesores.getApellidoM());
                txtTelefono.setText(asesores.getTelefono());
                txtEmail.setText(asesores.geteMail());
                cbbTipoEmpleado.setSelectedIndex(1);
                cbbTipoEmpleado.setSelectedItem("Asesor");
            }
        }
        
        ArrayList<Tecnico> tecnicos = sql.RetrieveTecnicos("select * from Empleados");
        for (Tecnico tec : tecnicos){
            if (tec.getId()== id){
                txtNombre.setText(tec.getNombre());
                txtApellidoP.setText(tec.getApellidoP());
                txtApellidoM.setText(tec.getApellidoM());
                txtTelefono.setText(tec.getTelefono());
                txtEmail.setText(tec.geteMail());
                cbbTipoEmpleado.setSelectedIndex(2);
                cbbTipoEmpleado.setSelectedItem("Tecnico");
                String level = tec.getNivelTecnico().toString();
                if (level.equals("Principiante")){
                    cbbNivel.setSelectedIndex(1);
                    cbbNivel.setSelectedItem(level);
                }else if(level.equals("Intermedio")){
                    cbbNivel.setSelectedIndex(2);
                    cbbNivel.setSelectedItem(level);
                }else if(level.equals("Master")){
                    cbbNivel.setSelectedIndex(3);
                    cbbNivel.setSelectedItem(level);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbbNivel;
    private javax.swing.JComboBox<String> cbbTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txtApellidoM;
    public javax.swing.JTextField txtApellidoP;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
